'use server'

import { createClient } from '@/lib/supabase/server'
import type { ApiResponse, CompanyProfile, PersonaData, BusinessContext } from '@/types'

export interface CompanyProfileWithBuyerPersonas {
  id: string
  user_id: string
  company_data: CompanyProfile
  created_at: string
  updated_at: string
  buyer_personas: BuyerPersonaListItem[]
}

export interface BuyerPersonaListItem {
  id: string
  company_profile_id: string
  persona_data: PersonaData
  created_at: string
}

/**
 * Fetch a company profile by ID with its linked buyer personas.
 */
export async function getCompanyProfile(
  companyProfileId: string
): Promise<ApiResponse<CompanyProfileWithBuyerPersonas>> {
  try {
    const supabase = createClient()

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return { success: false, error: 'Not authenticated' }
    }

    // Query company profile
    const { data: companyProfile, error: profileError } = await supabase
      .from('company_profiles')
      .select('*')
      .eq('id', companyProfileId)
      .single()

    if (profileError || !companyProfile) {
      console.error('Error fetching company profile:', profileError)
      return { success: false, error: 'Company profile not found' }
    }

    // Verify ownership
    if (companyProfile.user_id !== user.id) {
      return { success: false, error: 'Not authorized to view this company profile' }
    }

    // Fetch linked buyer personas
    const { data: buyerPersonas, error: buyerError } = await supabase
      .from('buyer_personas')
      .select('*')
      .eq('company_profile_id', companyProfileId)
      .order('created_at', { ascending: false })

    if (buyerError) {
      console.error('Error fetching buyer personas:', buyerError)
      // Don't fail, just return empty array
    }

    const result: CompanyProfileWithBuyerPersonas = {
      id: companyProfile.id,
      user_id: companyProfile.user_id,
      company_data: companyProfile.company_data as CompanyProfile,
      created_at: companyProfile.created_at,
      updated_at: companyProfile.updated_at,
      buyer_personas: (buyerPersonas || []).map((bp) => ({
        id: bp.id,
        company_profile_id: bp.company_profile_id,
        persona_data: bp.persona_data as PersonaData,
        created_at: bp.created_at,
      })),
    }

    return { success: true, data: result }
  } catch (err) {
    console.error('Unexpected error in getCompanyProfile:', err)
    return { success: false, error: 'An unexpected error occurred' }
  }
}

/**
 * Create a buyer persona linked to a company profile.
 * The persona_data is generated by the AI and passed in from the client.
 */
export async function createBuyerPersona(
  companyProfileId: string,
  personaData: PersonaData
): Promise<ApiResponse<{ id: string }>> {
  try {
    const supabase = createClient()

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return { success: false, error: 'Not authenticated' }
    }

    // Verify the company profile exists and user owns it
    const { data: companyProfile, error: profileError } = await supabase
      .from('company_profiles')
      .select('id, user_id')
      .eq('id', companyProfileId)
      .single()

    if (profileError || !companyProfile) {
      return { success: false, error: 'Company profile not found' }
    }

    if (companyProfile.user_id !== user.id) {
      return { success: false, error: 'Not authorized to add personas to this company' }
    }

    // Insert the buyer persona
    const { data: newBuyerPersona, error: insertError } = await supabase
      .from('buyer_personas')
      .insert({
        company_profile_id: companyProfileId,
        persona_data: personaData,
      })
      .select('id')
      .single()

    if (insertError || !newBuyerPersona) {
      console.error('Error creating buyer persona:', insertError)
      return { success: false, error: 'Failed to create buyer persona' }
    }

    return { success: true, data: { id: newBuyerPersona.id } }
  } catch (err) {
    console.error('Unexpected error in createBuyerPersona:', err)
    return { success: false, error: 'An unexpected error occurred' }
  }
}

/**
 * Get business context from a company profile for pre-filling the buyer persona wizard.
 * This extracts relevant context that can be used to generate a buyer persona.
 */
export async function getCompanyContext(
  companyProfileId: string
): Promise<ApiResponse<{ company_data: CompanyProfile; business_context: Partial<BusinessContext> }>> {
  try {
    const supabase = createClient()

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return { success: false, error: 'Not authenticated' }
    }

    // Query company profile
    const { data: companyProfile, error: profileError } = await supabase
      .from('company_profiles')
      .select('*')
      .eq('id', companyProfileId)
      .single()

    if (profileError || !companyProfile) {
      return { success: false, error: 'Company profile not found' }
    }

    // Verify ownership
    if (companyProfile.user_id !== user.id) {
      return { success: false, error: 'Not authorized to view this company profile' }
    }

    const companyData = companyProfile.company_data as CompanyProfile

    // Extract business context from company profile data
    // This provides context for generating buyer personas
    const businessContext: Partial<BusinessContext> = {
      business_name: companyData.name,
      business_sector: companyData.industry,
      target_location: companyData.location,
      company_size: companyData.size,
      industry: companyData.industry,
    }

    return {
      success: true,
      data: {
        company_data: companyData,
        business_context: businessContext,
      },
    }
  } catch (err) {
    console.error('Unexpected error in getCompanyContext:', err)
    return { success: false, error: 'An unexpected error occurred' }
  }
}
